### ISSUE TITLE
Raspberry 3 works

### ISSUE THREAD

**Issue by blfuentes** [NicoHood/Arduino#1]
Version 1.6.8 works with following setup
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

-------------------------------------
Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**Comment by NicoHood** [comment]
Thanks for the note!
Can you please also test this version and add a comment there?
https://github.com/arduino/Arduino/pull/4517

**Comment by Ghostbird** [comment]
I'm having issues because this happens on upload:
```
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:179)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.Sketch.upload(Sketch.java:1187)
	at processing.app.Sketch.exportApplet(Sketch.java:1161)
	at processing.app.Sketch.exportApplet(Sketch.java:1133)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2417)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at processing.app.helpers.StringReplacer.replaceFromMapping(StringReplacer.java:97)
	at processing.app.helpers.StringReplacer.replaceFromMapping(StringReplacer.java:89)
	at processing.app.helpers.StringReplacer.formatAndSplit(StringReplacer.java:37)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:174)
	... 6 more
```
```
$ uname -a
Linux athena 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
```
I'm not sure it's the program, or something completely different that messes with the upload. I checked the USB port, and board settings and it's set correctly.

**Comment by NicoHood** [comment]
You should post this bug on the official arduino github site. also there are official downloads available now. I will close my repository now, befor people start using old stuff
